
# Readme -Conexion base de datos 

Este documento explica cómo establecer la conexión a la base de datos MySQL en el proyecto de Biblioteca San Miguel, utilizando el conector JDBC en Java. Se debe de modificar los valores de configuración según tu entorno antes de ejecutar el código.

### Requisitos Previos

- **Java Development Kit (JDK):** Verifica que tienes instalada una versión compatible de Java (preferiblemente JDK 8 o superior).
- **MySQL Database:** La base de datos MySQL debe estar instalada y ejecutándose.
- **JDBC Driver:** Asegúrate de tener el conector MySQL JDBC en tu proyecto. Si estás utilizando Maven, agrega la siguiente dependencia a tu archivo `pom.xml`:

```xml
<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <version>8.0.32</version>
</dependency>
```

### Configuración de Conexión

Para conectarte a la base de datos, debes configurar los siguientes parámetros en el código Java:

```java
String url = "jdbc:mysql://localhost:3306/sistemabiblioteca";  // Dirección de la base de datos
String usuario = "root";  // Usuario de la base de datos
String contrasena = "Paquitosaurio";  // Contraseña de la base de datos
```

#### Ejemplo Adaptado para Otro Entorno:

Se necesita cambiar los datos para conectarse a la base de datos:

```java
String url = "jdbc:mysql://ip_del_servidor:3306/otra_base_de_datos";
String usuario = "otro_usuario";
String contrasena = "otra_contrasena";
```


### Código SQL para Crear las Tablas

Mediante este codigo se estaria creando las tablas:

```sql
-- Crear tabla Libros
CREATE TABLE Libros (
    id INT PRIMARY KEY AUTO_INCREMENT,
    isbn VARCHAR(50) NOT NULL,
    editorial VARCHAR(50) NOT NULL,
    edicion VARCHAR(50) NOT NULL
) ENGINE=InnoDB;

-- Crear tabla Monografias
CREATE TABLE Monografias (
    id INT PRIMARY KEY AUTO_INCREMENT,
    isbn VARCHAR(50) NOT NULL
) ENGINE=InnoDB;

-- Crear tabla Videos
CREATE TABLE Videos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    duracion VARCHAR(50) NOT NULL,
    formato VARCHAR(50) NOT NULL,
    productora VARCHAR(50) NOT NULL
) ENGINE=InnoDB;

-- Crear tabla Materiales
CREATE TABLE Materiales (
    id INT PRIMARY KEY AUTO_INCREMENT,
    titulo VARCHAR(50) NOT NULL,
    autor VARCHAR(50) NOT NULL,
    fechaPublicacion DATE NOT NULL,
    categoria VARCHAR(50) NOT NULL,
    estado VARCHAR(50) NOT NULL DEFAULT 'activo',
    idLibro INT,
    idMonografia INT,
    idVideo INT,
    FOREIGN KEY(idLibro) REFERENCES Libros(id),
    FOREIGN KEY(idMonografia) REFERENCES Monografias(id),
    FOREIGN KEY(idVideo) REFERENCES Videos(id)
) ENGINE=InnoDB;

-- Crear tabla Usuarios
CREATE TABLE Usuarios (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombres VARCHAR(50) NOT NULL,
    estado VARCHAR(15) NOT NULL DEFAULT 'activo'
) ENGINE=InnoDB;

-- Crear tabla Morosos
CREATE TABLE Morosos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    idUsuario INT,
    fechaExpiracion DATE NOT NULL,
    FOREIGN KEY(idUsuario) REFERENCES Usuarios(id)
) ENGINE=InnoDB;

-- Crear tabla Prestamos
CREATE TABLE Prestamos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    idMaterial INT,
    idUsuario INT,
    fechaPrestamo DATE NOT NULL,
    fechaLimite DATE NOT NULL,
    fechaDevolucion DATE,
    FOREIGN KEY(idMaterial) REFERENCES Materiales(id),
    FOREIGN KEY(idUsuario) REFERENCES Usuarios(id)
) ENGINE=InnoDB;

-- Crear tabla Reservas
CREATE TABLE Reservas (
    id INT PRIMARY KEY AUTO_INCREMENT,
    idMaterial INT,
    idUsuario INT,
    fechaRecogida DATE NOT NULL,
    efectuado VARCHAR(50) NOT NULL,
    cancelado VARCHAR(15) DEFAULT NULL,
    FOREIGN KEY(idMaterial) REFERENCES Materiales(id),
    FOREIGN KEY(idUsuario) REFERENCES Usuarios(id)
) ENGINE=InnoDB;
```

Este código SQL debe ser ejecutado en la base de datos MySQL para crear las tablas del proyecto.


# Readme - Conexión base de datos

Este documento explica cómo establecer la conexión a la base de datos MySQL en el proyecto de Biblioteca San Miguel, utilizando el conector JDBC en Java. Se debe modificar los valores de configuración según tu entorno antes de ejecutar el código.

### Requisitos Previos

- **Java Development Kit (JDK):** Verifica que tienes instalada una versión compatible de Java (preferiblemente JDK 8 o superior).
- **MySQL Database:** La base de datos MySQL debe estar instalada y ejecutándose.
- **JDBC Driver:** Asegúrate de tener el conector MySQL JDBC en tu proyecto. Si estás utilizando Maven, agrega la siguiente dependencia a tu archivo `pom.xml`:

```xml
<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <version>8.0.32</version> <!-- Asegúrate de usar la versión correcta -->
</dependency>
```

### Configuración de Conexión

Para conectarte a la base de datos, debes configurar los siguientes parámetros en el código Java:

```java
String url = "jdbc:mysql://localhost:3306/sistemabiblioteca";  // Dirección de la base de datos
String usuario = "root";  // Usuario de la base de datos
String contrasena = "Paquitosaurio";  // Contraseña de la base de datos
```

#### Ejemplo Adaptado para Otro Entorno:

En caso de necesitar conectarse a la base de datos en un servidor remoto, cambia la URL y ajusta las credenciales:

```java
String url = "jdbc:mysql://ip_del_servidor:3306/otra_base_de_datos";
String usuario = "otro_usuario";
String contrasena = "otra_contrasena";
```

### Código SQL para Crear las Tablas

A continuación se proporciona el código SQL necesario para crear las tablas en MySQL:

```sql
-- Crear tabla Libros
CREATE TABLE Libros (
    id INT PRIMARY KEY AUTO_INCREMENT,
    isbn VARCHAR(50) NOT NULL,
    editorial VARCHAR(50) NOT NULL,
    edicion VARCHAR(50) NOT NULL
) ENGINE=InnoDB;

-- Crear tabla Monografias
CREATE TABLE Monografias (
    id INT PRIMARY KEY AUTO_INCREMENT,
    isbn VARCHAR(50) NOT NULL
) ENGINE=InnoDB;

-- Crear tabla Videos
CREATE TABLE Videos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    duracion VARCHAR(50) NOT NULL,
    formato VARCHAR(50) NOT NULL,
    productora VARCHAR(50) NOT NULL
) ENGINE=InnoDB;

-- Crear tabla Materiales
CREATE TABLE Materiales (
    id INT PRIMARY KEY AUTO_INCREMENT,
    titulo VARCHAR(50) NOT NULL,
    autor VARCHAR(50) NOT NULL,
    fechaPublicacion DATE NOT NULL,
    categoria VARCHAR(50) NOT NULL,
    estado VARCHAR(50) NOT NULL DEFAULT 'activo',
    idLibro INT,
    idMonografia INT,
    idVideo INT,
    FOREIGN KEY(idLibro) REFERENCES Libros(id),
    FOREIGN KEY(idMonografia) REFERENCES Monografias(id),
    FOREIGN KEY(idVideo) REFERENCES Videos(id)
) ENGINE=InnoDB;

-- Crear tabla Usuarios
CREATE TABLE Usuarios (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombres VARCHAR(50) NOT NULL,
    estado VARCHAR(15) NOT NULL DEFAULT 'activo'
) ENGINE=InnoDB;

-- Crear tabla Morosos
CREATE TABLE Morosos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    idUsuario INT,
    fechaExpiracion DATE NOT NULL,
    FOREIGN KEY(idUsuario) REFERENCES Usuarios(id)
) ENGINE=InnoDB;

-- Crear tabla Prestamos
CREATE TABLE Prestamos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    idMaterial INT,
    idUsuario INT,
    fechaPrestamo DATE NOT NULL,
    fechaLimite DATE NOT NULL,
    fechaDevolucion DATE,
    FOREIGN KEY(idMaterial) REFERENCES Materiales(id),
    FOREIGN KEY(idUsuario) REFERENCES Usuarios(id)
) ENGINE=InnoDB;

-- Crear tabla Reservas
CREATE TABLE Reservas (
    id INT PRIMARY KEY AUTO_INCREMENT,
    idMaterial INT,
    idUsuario INT,
    fechaRecogida DATE NOT NULL,
    efectuado VARCHAR(50) NOT NULL,
    cancelado VARCHAR(15) DEFAULT NULL,
    FOREIGN KEY(idMaterial) REFERENCES Materiales(id),
    FOREIGN KEY(idUsuario) REFERENCES Usuarios(id)
) ENGINE=InnoDB;
```


### Notas Adicionales

- Si trabajas con un servidor MySQL en un puerto no estándar o con una configuración diferente (por ejemplo, SSL habilitado), asegúrate de ajustar la URL de conexión según sea necesario. Por ejemplo:

In [ ]:

# Readme - Conexión base de datos

Este documento explica cómo establecer la conexión a la base de datos MySQL en el proyecto de Biblioteca San Miguel, utilizando el conector JDBC en Java. Se debe modificar los valores de configuración según tu entorno antes de ejecutar el código.

### Requisitos Previos

- **Java Development Kit (JDK):** Verifica que tienes instalada una versión compatible de Java (preferiblemente JDK 8 o superior).
- **MySQL Database:** La base de datos MySQL debe estar instalada y ejecutándose.
- **JDBC Driver:** Asegúrate de tener el conector MySQL JDBC en tu proyecto. Si estás utilizando Maven, agrega la siguiente dependencia a tu archivo `pom.xml`:

```xml
<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <version>8.0.32</version> <!-- Asegúrate de usar la versión correcta -->
</dependency>
```

### Configuración de Conexión

Para conectarte a la base de datos, debes configurar los siguientes parámetros en el código Java:

```java
String url = "jdbc:mysql://localhost:3306/sistemabiblioteca";  // Dirección de la base de datos
String usuario = "root";  // Usuario de la base de datos
String contrasena = "Paquitosaurio";  // Contraseña de la base de datos
```

#### Ejemplo Adaptado para Otro Entorno:

En caso de necesitar conectarse a la base de datos en un servidor remoto, cambia la URL y ajusta las credenciales:

```java
String url = "jdbc:mysql://ip_del_servidor:3306/otra_base_de_datos";
String usuario = "otro_usuario";
String contrasena = "otra_contrasena";
```

### Código SQL para Crear las Tablas

A continuación se proporciona el código SQL necesario para crear las tablas en MySQL:

```sql
-- Crear tabla Libros
CREATE TABLE Libros (
    id INT PRIMARY KEY AUTO_INCREMENT,
    isbn VARCHAR(50) NOT NULL,
    editorial VARCHAR(50) NOT NULL,
    edicion VARCHAR(50) NOT NULL
) ENGINE=InnoDB;

-- Crear tabla Monografias
CREATE TABLE Monografias (
    id INT PRIMARY KEY AUTO_INCREMENT,
    isbn VARCHAR(50) NOT NULL
) ENGINE=InnoDB;

-- Crear tabla Videos
CREATE TABLE Videos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    duracion VARCHAR(50) NOT NULL,
    formato VARCHAR(50) NOT NULL,
    productora VARCHAR(50) NOT NULL
) ENGINE=InnoDB;

-- Crear tabla Materiales
CREATE TABLE Materiales (
    id INT PRIMARY KEY AUTO_INCREMENT,
    titulo VARCHAR(50) NOT NULL,
    autor VARCHAR(50) NOT NULL,
    fechaPublicacion DATE NOT NULL,
    categoria VARCHAR(50) NOT NULL,
    estado VARCHAR(50) NOT NULL DEFAULT 'activo',
    idLibro INT,
    idMonografia INT,
    idVideo INT,
    FOREIGN KEY(idLibro) REFERENCES Libros(id),
    FOREIGN KEY(idMonografia) REFERENCES Monografias(id),
    FOREIGN KEY(idVideo) REFERENCES Videos(id)
) ENGINE=InnoDB;

-- Crear tabla Usuarios
CREATE TABLE Usuarios (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombres VARCHAR(50) NOT NULL,
    estado VARCHAR(15) NOT NULL DEFAULT 'activo'
) ENGINE=InnoDB;

-- Crear tabla Morosos
CREATE TABLE Morosos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    idUsuario INT,
    fechaExpiracion DATE NOT NULL,
    FOREIGN KEY(idUsuario) REFERENCES Usuarios(id)
) ENGINE=InnoDB;

-- Crear tabla Prestamos
CREATE TABLE Prestamos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    idMaterial INT,
    idUsuario INT,
    fechaPrestamo DATE NOT NULL,
    fechaLimite DATE NOT NULL,
    fechaDevolucion DATE,
    FOREIGN KEY(idMaterial) REFERENCES Materiales(id),
    FOREIGN KEY(idUsuario) REFERENCES Usuarios(id)
) ENGINE=InnoDB;

-- Crear tabla Reservas
CREATE TABLE Reservas (
    id INT PRIMARY KEY AUTO_INCREMENT,
    idMaterial INT,
    idUsuario INT,
    fechaRecogida DATE NOT NULL,
    efectuado VARCHAR(50) NOT NULL,
    cancelado VARCHAR(15) DEFAULT NULL,
    FOREIGN KEY(idMaterial) REFERENCES Materiales(id),
    FOREIGN KEY(idUsuario) REFERENCES Usuarios(id)
) ENGINE=InnoDB;
```

Este código SQL debe ser ejecutado en tu base de datos MySQL para crear las tablas necesarias para el proyecto.

### Conexión y Manejo de Errores

A continuación, el código para establecer la conexión y manejar posibles excepciones:

```java
try {
    Connection conexion = DriverManager.getConnection(url, usuario, contrasena);
    System.out.println("Conexión exitosa!");
} catch (SQLException e) {
    System.err.println("Error de conexión: " + e.getMessage());
    // Aquí puedes añadir más lógica para manejar el error según sea necesario
}
```

### Recomendaciones

- **Testing Local:** Si trabajas en un entorno local, asegúrate de que MySQL esté corriendo y de que la base de datos esté accesible a través de la red local.
- **Seguridad:** No dejes tus credenciales de base de datos hardcodeadas en el código. Considera usar un archivo de configuración o variables de entorno para mayor seguridad en producción.
- **Optimización:** En un entorno de producción, considera el uso de un `DataSource` en lugar de conectar directamente usando `DriverManager`, para mejorar el rendimiento y la gestión de conexiones.

### Notas Adicionales

- Si trabajas con un servidor MySQL en un puerto no estándar o con una configuración diferente (por ejemplo, SSL habilitado), asegúrate de ajustar la URL de conexión según sea necesario. Por ejemplo: